FROM opencpu/rstudio

RUN R -e 'install.packages(c("devtools"), repos="https://cran.rstudio.com/")'

## need to get spatial stuff going as well
## install all the dependencies
## install_github the package itself
## add/copy the files into a folder
## set package options to use local copy

